# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='rum_message.proto',
  package='',
  serialized_pb='\n\x11rum_message.proto\"}\n\nRumMessage\x12\x1e\n\x04type\x18\x01 \x02(\x0e\x32\x10.RumMessage.Type\x12\x16\n\x0e\x62inary_payload\x18\x02 \x01(\x0c\x12\x0f\n\x07payload\x18\x03 \x01(\t\"&\n\x04Type\x12\x08\n\x04JSON\x10\x00\x12\x08\n\x04\x42SON\x10\x01\x12\n\n\x06\x42INARY\x10\x02')



_RUMMESSAGE_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='RumMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='JSON', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BSON', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BINARY', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=108,
  serialized_end=146,
)


_RUMMESSAGE = descriptor.Descriptor(
  name='RumMessage',
  full_name='RumMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='RumMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='binary_payload', full_name='RumMessage.binary_payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payload', full_name='RumMessage.payload', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RUMMESSAGE_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=146,
)

_RUMMESSAGE.fields_by_name['type'].enum_type = _RUMMESSAGE_TYPE
_RUMMESSAGE_TYPE.containing_type = _RUMMESSAGE;
DESCRIPTOR.message_types_by_name['RumMessage'] = _RUMMESSAGE

class RumMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RUMMESSAGE
  
  # @@protoc_insertion_point(class_scope:RumMessage)

# @@protoc_insertion_point(module_scope)
