# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='auth.proto',
  package='',
  serialized_pb='\n\nauth.proto\"\xc9\x01\n\x0b\x41uthMessage\x12\x1f\n\x04type\x18\x01 \x02(\x0e\x32\x11.AuthMessage.Type\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\r\n\x05nonce\x18\x03 \x01(\t\x12\x10\n\x08response\x18\x04 \x01(\t\x12\r\n\x05token\x18\x05 \x01(\t\x12\x15\n\rerror_message\x18\x06 \x01(\t\"D\n\x04Type\x12\r\n\tCHALLENGE\x10\x01\x12\x0c\n\x08RESPONSE\x10\x02\x12\t\n\x05TOKEN\x10\x03\x12\t\n\x05HELLO\x10\x04\x12\t\n\x05\x45RROR\x10\x05')



_AUTHMESSAGE_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='AuthMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='CHALLENGE', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TOKEN', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='HELLO', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ERROR', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=148,
  serialized_end=216,
)


_AUTHMESSAGE = descriptor.Descriptor(
  name='AuthMessage',
  full_name='AuthMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='AuthMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='AuthMessage.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nonce', full_name='AuthMessage.nonce', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='response', full_name='AuthMessage.response', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='token', full_name='AuthMessage.token', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error_message', full_name='AuthMessage.error_message', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AUTHMESSAGE_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=15,
  serialized_end=216,
)

_AUTHMESSAGE.fields_by_name['type'].enum_type = _AUTHMESSAGE_TYPE
_AUTHMESSAGE_TYPE.containing_type = _AUTHMESSAGE;
DESCRIPTOR.message_types_by_name['AuthMessage'] = _AUTHMESSAGE

class AuthMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTHMESSAGE
  
  # @@protoc_insertion_point(class_scope:AuthMessage)

# @@protoc_insertion_point(module_scope)
